site_name: Awesome Docs
strict: true
nav:
    - Home: ../README.md
    - Docs: index.md
    - "Architecture": architecture/README.md
    - "Search bank": architecture/2-searchBank.md
theme: readthedocs
